In [1]:
##Install msoffcrypto-tool:
##pip install msoffcrypto-tool

In [17]:
import io

import msoffcrypto
import openpyxl
from openpyxl import load_workbook
import numpy as np
import pandas as pd

In [18]:
decrypted_workbook = io.BytesIO()

with open('Desktop\Final Walkthrough.xlsx', 'rb') as file:
    office_file = msoffcrypto.OfficeFile(file)
    office_file.load_key(password='123')
    office_file.decrypt(decrypted_workbook)

# `filename` can also be a file-like object.

In [19]:
wb = load_workbook(filename=decrypted_workbook)

In [20]:
print(wb.sheetnames)

['Sheet1', 'Electricity', 'Hilton Managaed - Trust ']


In [21]:
temp = [('Electricity'), ('Hilton Managaed - Trust')]

In [22]:
def get_ly_month_data(tab, date):
    wb = wb = openpyxl.load_workbook(filename=decrypted_workbook, data_only=True)
    try:
        ws = wb[tab]
    except KeyError:
        return np.zeros(7-3)
    dates = []
    for each in list(ws[1]):
        dates.append(each.value)
        
    ly_month_col = dates.index(date)
    ly_month_data = []
    for i in range(3,7,1):
        ly_month_data.append(ws.cell(column = ly_month_col+1, row = i).value)
    return np.array([0 if x==None else x for x in ly_month_data])

In [23]:
get_ly_month_data('Electricity', 'Apr - 20')

array([24.864 ,  0.    ,  0.    , 20.9568])

In [24]:
temp = ['Electricity', 'Hilton Managaed - Trust']

In [25]:
df_result = pd.DataFrame()

for item in temp:
    ly_month_data = get_ly_month_data(item[0], 'Apr - 20')
    print(ly_month_data)
    #ly_month_data_2 = get_ly_month_data(item[1], 'Apr - 20')
    #ly_month_data_2 = get_ly_month_data('Electricity', 'Apr - 20')
    df_result[item.split(" ")[0]+" Apr-20"] = ly_month_data
    #print(get_ly_month_data(item[0], 'Apr - 20'))
    
print(df_result)

[0. 0. 0. 0.]
[0. 0. 0. 0.]
   Electricity Apr-20  Hilton Apr-20
0                 0.0            0.0
1                 0.0            0.0
2                 0.0            0.0
3                 0.0            0.0
